services:
    piotrowm_invoice_storage.netPriceCalculator:
        class: Piotrowm\InvoiceStorageBundle\Service\NetPriceCalculator
        arguments: []
    piotrowm_invoice_storage.customerDataLoader:
        class: Piotrowm\InvoiceStorageBundle\Service\CustomerDataLoader
        arguments: []
    piotrowm_invoice_storage.shipmentLoader:
        class: Piotrowm\InvoiceStorageBundle\Service\ShipmentLoader
        arguments: []
